app = "disneybound-planner"
primary_region = "sjc"

[build]

[deploy]
  release_command = "uv run python manage.py migrate"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  DJANGO_SETTINGS_MODULE = "config.settings"
